use_frameworks!

target 'FirstCocoapodsProject_Example' do
  pod 'FirstCocoapodsProject', :path => '../'

  target 'FirstCocoapodsProject_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
